### ISSUE TITLE
Gold User Coins has an invalid .geode file

### ISSUE THREAD

**Issue by anti-25** [GDColon/Gold-User-Coins#7]
The mod doesn't work, error details:

mod.json uses old syntax

![Screenshot 2024-06-28 175547](https://github.com/GDColon/Gold-User-Coins/assets/174156972/9873831f-c9a3-46d8-9d28-0964107f4712)

![Screenshot 2024-06-28 175624](https://github.com/GDColon/Gold-User-Coins/assets/174156972/3dd7b760-3df7-4f97-b94b-fec1fd01fa62)

![Screenshot 2024-06-28 175707](https://github.com/GDColon/Gold-User-Coins/assets/174156972/f52cc1c6-7333-4058-a913-7492a5f20063)

**Comment by GDColon** [comment]
This mod has not been updated for 2.206 yet, since it requires patching the game.

**Comment by anti-25** [comment]
And this is why I love GD Cologne
