### ISSUE TITLE
"mod.json uses old syntax"

### ISSUE THREAD

**Issue by Chreestafunni** [GDColon/Gold-User-Coins#8]
I think a recent Geode/GD update broke this mod, because I'm receiving error messages saying that it has an invalid .geode file.

![ssgd](https://github.com/GDColon/Gold-User-Coins/assets/174908969/4d6d5e6b-8430-449a-8ab0-80db252ab731)
![ssgd2](https://github.com/GDColon/Gold-User-Coins/assets/174908969/2bfe3449-dab2-43eb-92e1-2610e17d219e)

**Comment by GDColon** [comment]
This mod has not been updated for 2.206
